---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: varasheswar/container:db
   ports:
     - "3306:3306"

 application:
   image: varasheswar/container:app
   container_name: appcontainer
   ports:
     - "1323:8080"
   depends_on:
     - "devopsdb"
